version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 16

pre_build:
  commands:
    - echo nothing


build:
  commands:
    - echo Build start on 'date'
    - npm install
    - echo npm completed on 'date'
    - npm run build
    - echo npm run build completed on 'date'

post_build:
  commands:
    - echo Build completed on 'date'
    - ls -l ./dist/shop/

aritifacts:
  files:
    - dist/shop/
    - dist/shop/assets/*
    - appspec.yaml
